services:
  db:
    image: mysql:8
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 4s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: arriendatufinca
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - arriendatufinca-network

  app:
    image: localhost:5000/arriendatufinca:latest
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/arriendatufinca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy  
    networks:
      - arriendatufinca-network

volumes:
  db_data:

networks:
  arriendatufinca-network: