apiVersion: apps/v1
kind: Deployment
metadata:
  name: arriendatufinca
  namespace: arriendatufinca
spec:
  selector:
    matchLabels:
      app: arriendatufinca
  replicas: 1
  template:
    metadata:
      labels:
         app: arriendatufinca
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: estudiante
           image: localhost:5000/arriendatufinca:latest
           ports:
              - containerPort: 8080
           env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:mysql://db:3306/arriendatufinca
              - name: SPRING_DATASOURCE_USERNAME
                value: root
              - name: SPRING_DATASOURCE_PASSWORD
                value: "12345"
           
---
apiVersion: v1
kind: Service
metadata:
  name: arriendatufinca
  namespace: arriendatufinca
spec:
  selector:
    app: estudiante
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
