apiVersion: apps/v1
kind: Deployment
metadata:
  name: arriendatufinca
  namespace: arriendatufinca
spec:
  selector:
    matchLabels:
      app: arriendatufinca
  replicas: 1
  template:
    metadata:
      labels:
         app: arriendatufinca
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: estudiante
           image: localhost:5000/arriendatufinca:latest
           ports:
              - containerPort: 8080
           env:
              - name: DB_HOST
                value: "db"
              - name: DB_PORT
                value: "3306"
              - name: DB_USER
                value: "user"
              - name: DB_PASSWORD
                value: "12345"
           
---
apiVersion: v1
kind: Service
metadata:
  name: arriendatufinca
  namespace: arriendatufinca
spec:
  selector:
    app: estudiante
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
